import { useState } from 'react';
import { toast } from 'react-hot-toast';
import {
  Plus, Copy, Download, ChevronDown,
  Briefcase, Building2, CheckCircle2, FileText, FileDown
} from 'lucide-react';
import { getDownloadUrl } from '../api';

export default function ReportView({ data, text, taskId, onNewAnalysis }) {
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [activeTab, setActiveTab] = useState('report'); // 'report' | 'raw'

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      toast.success('Copied to clipboard');
    } catch {
      toast.error('Failed to copy');
    }
  };

  const handleDownload = (format) => {
    setShowExportMenu(false);
    const url = getDownloadUrl(taskId, format);
    const a = document.createElement('a');
    a.href = url;
    a.download = `clauseai_report_${taskId}.${format}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    toast.success(`Downloading as ${format.toUpperCase()}`);
  };

  return (
    <div style={styles.card} className="animate-scale-in">
      {/* Header */}
      <div style={styles.header}>
        <div style={styles.headerLeft}>
          <h2 style={styles.title}>Contract Analysis Report</h2>
          <p style={styles.meta}>Task {taskId} &bull; Generated by ClauseAI</p>
        </div>
        <div style={styles.actions}>
          <button onClick={onNewAnalysis} style={styles.btnGhost}>
            <Plus size={14} />
            New
          </button>
          <button onClick={handleCopy} style={styles.btn}>
            <Copy size={14} />
            Copy
          </button>
          <div style={{ position: 'relative' }}>
            <button
              onClick={() => setShowExportMenu(!showExportMenu)}
              style={styles.btnAccent}
            >
              <Download size={14} />
              Export
              <ChevronDown size={12} />
            </button>
            {showExportMenu && (
              <>
                <div
                  style={styles.menuBackdrop}
                  onClick={() => setShowExportMenu(false)}
                />
                <div style={styles.exportMenu}>
                  <button onClick={() => handleDownload('pdf')} style={styles.menuItem}>
                    <FileDown size={14} style={{ color: '#ef4444' }} />
                    <div>
                      <p style={styles.menuLabel}>PDF Document</p>
                      <p style={styles.menuDesc}>Standard portable format</p>
                    </div>
                  </button>
                  <button onClick={() => handleDownload('docx')} style={styles.menuItem}>
                    <FileDown size={14} style={{ color: '#3b82f6' }} />
                    <div>
                      <p style={styles.menuLabel}>Word Document</p>
                      <p style={styles.menuDesc}>Editable .docx format</p>
                    </div>
                  </button>
                  <button onClick={() => handleDownload('txt')} style={styles.menuItem}>
                    <FileText size={14} style={{ color: 'var(--text-muted)' }} />
                    <div>
                      <p style={styles.menuLabel}>Plain Text</p>
                      <p style={styles.menuDesc}>Simple .txt format</p>
                    </div>
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Tags */}
      <div style={styles.tags}>
        <Tag icon={<Briefcase size={12} />} label={data.contract_type || 'Unknown'} />
        <Tag icon={<Building2 size={12} />} label={data.industry || 'General'} />
        <Tag icon={<CheckCircle2 size={12} />} label="Completed" color="var(--success)" />
      </div>

      {/* Tab switcher */}
      <div style={styles.tabBar}>
        <button
          onClick={() => setActiveTab('report')}
          style={activeTab === 'report' ? styles.tabActive : styles.tab}
        >
          Formatted Report
        </button>
        <button
          onClick={() => setActiveTab('raw')}
          style={activeTab === 'raw' ? styles.tabActive : styles.tab}
        >
          Raw Text
        </button>
      </div>

      {/* Report content */}
      <div style={styles.reportContainer}>
        {activeTab === 'report' ? (
          <div
            className="rpt-content"
            style={styles.reportContent}
            dangerouslySetInnerHTML={{ __html: renderReport(text) }}
          />
        ) : (
          <pre style={styles.rawText}>{text}</pre>
        )}
      </div>
    </div>
  );
}

function Tag({ icon, label, color }) {
  return (
    <span style={{
      ...tagStyles.tag,
      ...(color ? { borderColor: color + '33', color } : {}),
    }}>
      {icon}
      {label}
    </span>
  );
}

const tagStyles = {
  tag: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-full)',
    background: 'var(--bg-input)',
    color: 'var(--text-secondary)',
    padding: '5px 14px',
    fontSize: 12,
    fontWeight: 500,
  },
};

function renderReport(text) {
  let s = text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  // Structural
  s = s.replace(/^={3,}.*$/gm, '<hr class="rpt-hr">');
  s = s.replace(/^### (.+)$/gm, '<h3 class="rpt-h3">$1</h3>');
  s = s.replace(/^## (.+)$/gm, '<h2 class="rpt-h2">$1</h2>');
  s = s.replace(/^# (.+)$/gm, '<h1 class="rpt-h1">$1</h1>');

  // Inline
  s = s.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');

  // Risk badges
  s = s.replace(
    /Risk Level:\s*High/gi,
    'Risk Level: <span class="rpt-risk rpt-risk-high">High</span>'
  );
  s = s.replace(
    /Risk Level:\s*Medium/gi,
    'Risk Level: <span class="rpt-risk rpt-risk-medium">Medium</span>'
  );
  s = s.replace(
    /Risk Level:\s*Low/gi,
    'Risk Level: <span class="rpt-risk rpt-risk-low">Low</span>'
  );

  // Status badges in clause analysis
  s = s.replace(
    /\[PRESENT\]/g,
    '<span class="rpt-badge rpt-badge-present">PRESENT</span>'
  );
  s = s.replace(
    /\[MISSING\/WEAK\]/g,
    '<span class="rpt-badge rpt-badge-missing">MISSING/WEAK</span>'
  );

  // Lists
  s = s.replace(/^[-*] (.+)$/gm, '<li>$1</li>');
  s = s.replace(/((?:<li>.*<\/li>\n?)+)/g, '<ul>$1</ul>');
  // Remove newlines between list items (prevents <br> inside <ul>)
  s = s.replace(/<ul>\n/g, '<ul>');
  s = s.replace(/\n<\/ul>/g, '</ul>');
  s = s.replace(/<\/li>\n<li>/g, '</li><li>');

  // Paragraphs
  s = s.replace(/\n{2,}/g, '</p><p>');
  s = s.replace(/\n/g, '<br>');
  s = '<p>' + s + '</p>';

  // Clean up empty and misplaced tags
  s = s.replace(/<p>\s*<\/p>/g, '');
  s = s.replace(/<p>\s*(<h[1-3])/g, '$1');
  s = s.replace(/(<\/h[1-3]>)\s*<\/p>/g, '$1');
  s = s.replace(/<p>\s*(<hr)/g, '$1');
  s = s.replace(/(<hr[^>]*>)\s*<\/p>/g, '$1');
  s = s.replace(/<p>\s*(<ul>)/g, '$1');
  s = s.replace(/(<\/ul>)\s*<\/p>/g, '$1');

  return s;
}

const styles = {
  card: {
    background: 'var(--bg-card)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-lg)',
    padding: 0,
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    padding: '20px 24px',
    borderBottom: '1px solid var(--border)',
  },
  headerLeft: {
    minWidth: 0,
  },
  title: {
    fontFamily: 'var(--font-serif)',
    fontSize: 20,
    fontWeight: 700,
    letterSpacing: '-0.02em',
  },
  meta: {
    fontSize: 13,
    color: 'var(--text-muted)',
    marginTop: 3,
  },
  actions: {
    display: 'flex',
    gap: 8,
    flexShrink: 0,
    alignItems: 'center',
  },
  btn: {
    height: 34,
    padding: '0 14px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)',
    background: 'var(--bg-elevated)',
    color: 'var(--text-secondary)',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: 'inherit',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    cursor: 'pointer',
    transition: 'all 200ms',
  },
  btnGhost: {
    height: 34,
    padding: '0 14px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid transparent',
    background: 'transparent',
    color: 'var(--text-muted)',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: 'inherit',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    cursor: 'pointer',
    transition: 'all 200ms',
  },
  btnAccent: {
    height: 34,
    padding: '0 14px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--accent)',
    background: 'var(--accent-muted)',
    color: 'var(--accent-hover)',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: 'inherit',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    cursor: 'pointer',
    transition: 'all 200ms',
  },
  menuBackdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 40,
  },
  exportMenu: {
    position: 'absolute',
    top: 'calc(100% + 6px)',
    right: 0,
    width: 240,
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    boxShadow: 'var(--shadow-lg)',
    padding: 6,
    zIndex: 50,
    animation: 'slideDown 0.15s ease',
  },
  menuItem: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '10px 12px',
    border: 'none',
    borderRadius: 'var(--radius-sm)',
    background: 'transparent',
    color: 'var(--text-primary)',
    fontFamily: 'inherit',
    cursor: 'pointer',
    transition: 'background 150ms',
    textAlign: 'left',
  },
  menuLabel: {
    fontSize: 13,
    fontWeight: 600,
  },
  menuDesc: {
    fontSize: 11,
    color: 'var(--text-muted)',
    marginTop: 1,
  },
  tags: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
    padding: '14px 24px',
  },
  tabBar: {
    display: 'flex',
    gap: 0,
    padding: '0 24px',
    borderBottom: '1px solid var(--border)',
  },
  tab: {
    padding: '10px 18px',
    border: 'none',
    borderBottom: '2px solid transparent',
    background: 'transparent',
    color: 'var(--text-muted)',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: 'inherit',
    cursor: 'pointer',
    transition: 'all 150ms',
  },
  tabActive: {
    padding: '10px 18px',
    border: 'none',
    borderBottom: '2px solid var(--accent)',
    background: 'transparent',
    color: 'var(--accent)',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: 'inherit',
    cursor: 'pointer',
  },
  reportContainer: {
    maxHeight: 650,
    overflow: 'auto',
    padding: '20px 24px',
  },
  reportContent: {
    fontSize: 14,
    lineHeight: 1.75,
    color: 'var(--text-primary)',
  },
  rawText: {
    fontSize: 13,
    lineHeight: 1.7,
    color: 'var(--text-secondary)',
    fontFamily: 'var(--font-mono)',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    margin: 0,
  },
};

// Inject report CSS into document
const reportCSS = `
.rpt-hr { border: 0; border-top: 1px solid var(--border); margin: 18px 0; }
.rpt-h1 { font-family: var(--font-serif); font-size: 20px; font-weight: 700; margin: 20px 0 10px; color: var(--text-primary); }
.rpt-h2 { font-family: var(--font-serif); font-size: 17px; font-weight: 600; margin: 18px 0 8px; padding-bottom: 6px; border-bottom: 1px solid var(--border); color: var(--text-primary); }
.rpt-h3 { font-size: 15px; font-weight: 600; margin: 14px 0 6px; color: var(--text-primary); }
.rpt-risk { font-weight: 700; padding: 2px 10px; border-radius: 4px; font-size: 13px; }
.rpt-risk-high { color: #ef4444; background: var(--danger-muted); }
.rpt-risk-medium { color: #f59e0b; background: var(--warning-muted); }
.rpt-risk-low { color: #22c55e; background: var(--success-muted); }
.rpt-badge { font-size: 11px; font-weight: 700; padding: 2px 8px; border-radius: 4px; letter-spacing: 0.04em; }
.rpt-badge-present { color: #22c55e; background: var(--success-muted); }
.rpt-badge-missing { color: #ef4444; background: var(--danger-muted); }
.rpt-content ul { margin: 8px 0 8px 20px; }
.rpt-content li { margin-bottom: 4px; color: var(--text-secondary); }
.rpt-content strong { color: var(--text-primary); font-weight: 600; }
`;

if (typeof document !== 'undefined' && !document.getElementById('clauseai-report-styles')) {
  const style = document.createElement('style');
  style.id = 'clauseai-report-styles';
  style.textContent = reportCSS;
  document.head.appendChild(style);
}
